---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../odh-common/base
  #
  - ../../odh-dashboard/base
  - ../../odh-dashboard/overlays/authentication
#  - ../../odh-dashboard/overlays/odhdashboardconfig
#  - ../../odh-dashboard/crd
  #
  #- ../../prometheus/cluster/base
  #
#  - ../../prometheus/operator/base
#  - ../../prometheus/operator/overlays/kubeflow
  #
  #- ../../grafana/cluster/base
  #
  #- ../../grafana/grafana/base
  #
  #- ../../odh-notebook-controller/base
  #
  #- ../../notebook-images/base
  #
#  - ../../model-mesh/base
#  - ../../model-mesh/overlays/odh-model-controller
#  - ../../model-mesh/crd
  #
#  - ../../data-science-pipelines/base
#  - ../../data-science-pipelines/overlay/metadata-store-mariadb
#  - ../../data-science-pipelines/overlay/ds-pipeline-ui
#  - ../../data-science-pipelines/overlay/object-store-minio
#  - ../../data-science-pipelines/overlay/default-configs

replacements:
# Update odh-common-config ConfigMap
- path: replacement.yaml
# Make sure that the new namespace is labeled for ArgoCD to manage it
- source:
    kind: Namespace
    name: opendatahub
    fieldPath: metadata.annotations.[argocd.argoproj.io/managed-by]
  targets:
    - select:
        kind: Namespace
        name: opendatahub
      fieldPaths:
        - metadata.labels.[argocd.argoproj.io/managed-by]
      options:
        create: true
# Update the name of the namespace
- source:
    kind: Namespace
    name: opendatahub
    fieldPath: metadata.annotations.team/namespace
  targets:
    - select:
        kind: Namespace
        name: opendatahub
      fieldPaths:
        - metadata.name
# Update the namespace for the OperatorGroup
- source:
    kind: OperatorGroup
    name: opendatahub
    fieldPath: metadata.annotations.team/namespace
  targets:
    - select:
        kind: OperatorGroup
        name: opendatahub
      fieldPaths:
        - metadata.namespace
# Specify a namespace for the ClusterRoleBinding subjects
- source:
    kind: ClusterRoleBinding
    name: odh-dashboard-monitoring
    fieldPath: metadata.annotations.team/namespace
  targets:
    - select:
        kind: ClusterRoleBinding
        name: odh-dashboard-monitoring
      fieldPaths:
        - subjects.[name=odh-dashboard].namespace
      options:
        create: true
